### PR TITLE
Remove mentions of tools

### PR DESCRIPTION
**Pull request by andyw8**
As discussed in #85.

### CODE REVIEW

**Comment by bbatsov** [comment]
👍

**Comment by pirj** [comment]
Agree that this doesn't belong to the style guide per se.
Those are helpful tips though, along with many others not mentioned (e.g. `--only-failures` flag). Any suggestions where to put those so it doesn't fall through the cracks?

**Comment by bbatsov** [comment]
I guess we can add a second document in the repo focused on tips, tricks and additional info. Maybe there's some better approach, though.

**Comment by andyw8** [comment]
I think that between the docs, books, and various blog posts, these topics are already covered sufficiently.

**Comment by bbatsov** [comment]
Agreed.

**Pull request merged**
