### PR TITLE
Introduce a rule describing when to use `specify` over `it`

### PR DESCRIPTION
**Pull request by pirj**

### CODE REVIEW

**Comment by bbatsov** [comment]
👍

**Comment by bbatsov** [comment]
On a related note - I don't think there's anything in the guide on the proper usage of `specify`.  Frankly, I've never really needed it, but I guess we should outline some good use cases for it.

**Comment by bbatsov** [comment]
There's even https://github.com/rubocop-hq/rspec-style-guide/issues/14 😆

**Comment by pirj** [comment]
I came up with this mainly to address #14. I think in general it makes sense to use `specify` instead of `it` where `it` doesn't fit into the sentence when you read the code, e.g.
```
specify do
  expect(user).to be_valid
end
```
`it` just doesn't sound right in this context. I can't say that `specify` sounds any better though.

**Comment by pirj** [comment]
Is it ok to merge as is, or does it make sense to add a section with some good examples for `specify`?

**Comment by bbatsov** [comment]
I'm OK with merging this, but I still think that at some point we should explain when to use `specify`.

**Pull request merged**
